name: Create-AppImage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libssl-dev qtbase5-dev qt5-qmake

      - name: Clone Blink repository
        run: git clone https://github.com/AGProjects/blink-qt.git && cd blink-qt

      - name: Download encryption key
        run: sudo wget -O /usr/share/keyrings/agp-debian-key.gpg http://download.ag-projects.com/agp-debian-key.gpg

      - name: Create sources list file
        run: echo "deb [signed-by=/usr/share/keyrings/agp-debian-key.gpg] https://packages.ag-projects.com/debian stretch main
            deb-src [signed-by=/usr/share/keyrings/agp-debian-key.gpg] https://packages.ag-projects.com/debian stretch main" | sudo tee /etc/apt/sources.list.d/ag-projects.list

      - name: Update package list
        run: sudo apt-get update

      - name: Install package Blink
        run: sudo apt-get install -y blink

      - name: Download linuxdeployqt
        run: |
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-continuous-x86_64.AppImage

      - name: Create AppImage
        run: |
          ./linuxdeployqt-continuous-x86_64.AppImage ./bin/blink -appimage
